version: "3.9"
services:
  eventstore:
    build:
      context: .
      dockerfile: Dockerfile
    image: daniloneto/lockfree-eventstore:local
    container_name: lf_eventstore
    ports:
      - "7070:7070"

  gateway:
    build:
      context: .
      dockerfile: samples/GatewayClient/Dockerfile
    environment:
      - EVENTSTORE_URL=http://eventstore:7070
    depends_on:
      - eventstore
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:alpine
    container_name: lf_nginx
    depends_on:
      - gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

# Build & run locally: docker compose up --build -d
# Scale gateways: docker compose up -d --scale gateway=5
