name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - run: dotnet build src/LockFree.EventStore/LockFree.EventStore.csproj -c Release
      - name: Test with coverage and threshold
        run: |
          dotnet test tests/LockFree.EventStore.Tests/LockFree.EventStore.Tests.csproj -c Release --no-build \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=TestResults/coverage/ \
            /p:Threshold=80 \
            /p:ThresholdType=line \
            /p:ThresholdStat=total
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: tests/LockFree.EventStore.Tests/TestResults/coverage/**
