name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build src/LockFree.EventStore/LockFree.EventStore.csproj --no-restore
      - name: Test
        run: dotnet test src/LockFree.EventStore/LockFree.EventStore.csproj --no-build
