name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      - run: dotnet build src/LockFree.EventStore/LockFree.EventStore.csproj -c Release
      - run: dotnet test tests/LockFree.EventStore.Tests/LockFree.EventStore.Tests.csproj -c Release --no-build
